--- 
driver: 
  name: ec2 
  aws_ssh_key_id: aha-kp 
  #aws_ssh_key_id: my-ssh-key 
  region: us-east-1 
  availability_zone: b 
  subnet_id: subnet-92ab02db  
  #subnet_id: subnet-xxxxxxxx 
  instance_type: t2.micro 
  image_id: ami-0b33d91d 
  security_group_ids: ['sg-e3130399'] 
  #security_group_ids: ['sg-xxxxxxxx'] 
  retryable_tries: 120 
provisioner: 
  name: chef_solo 
 
transport: 
  username: ec2-user   
  ssh_key: /Users/REANEmployee/Desktop/aha-kp.pem 
  #ssh_key: /Users/REANEmployee/Desktop/my-ssh-key.pem 
 
platforms: 
   - name: amazon 
