Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "amazon-linux-2013.09-x64-ebs"
  c.vm.hostname = "default-amazon-linux-201309-x64-ebs"
    c.ssh.username = "ec2-user"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
  end
end
